/* Bring the webfonts into the repo, so the browser never has to swap them in.
   node tools/fetch-fonts.mjs

   Why this exists. The fonts were loaded from Google, which means the first
   paint of every page uses a fallback face and the real one replaces it a
   moment later. Text measured in the fallback is a slightly different width, so
   the page re-lays-out under the visitor: the wordmark in the nav moved 2.83px
   and the Menus button 1.88px on every navigation, and on the menu pages a
   re-wrapped lede moved the masthead's bottom edge — a hard colour seam across
   the whole page — by 31.5px.

   styles.css already carries metric-matched fallback faces to shrink that gap,
   and they took it from roughly 12px down to under 3px. Under 3px is still
   visible on a fixed bar you see on every page, and no amount of further
   tuning reaches zero, because size-adjust is one ratio for a whole face while
   individual letters differ. The only way to zero is for there to be no swap.

   Self-hosted and preloaded, the font is requested alongside the stylesheet
   from the same origin and is normally in place for the first paint. It also
   matches what this project already does everywhere else: admin.html loads the
   Supabase SDK from vendor/, never a CDN. The fonts were the last exception.

   Both families are SIL Open Font License, which permits this. The licence is
   written next to the files.

   Re-run this if the font stack in the page ever changes. It rewrites the
   block between the markers in styles.css and nothing else. */

import { writeFileSync, readFileSync, mkdirSync } from "node:fs";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,300;1,9..144,400" +
  "&family=Manrope:wght@300;400;500;600;700&display=swap";

/* A modern browser's UA, or Google serves the old truetype CSS instead of the
   variable woff2 one. */
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
           "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

/* The site is English with a few accented characters — Café, crêpe, the
   Georgian dish names in Latin transliteration. latin and latin-ext cover all
   of it. Cyrillic, Greek and Vietnamese are dropped: the browser would never
   request them, and they are files someone has to drag onto Cloudflare. */
const SUBSETS = new Set(["latin", "latin-ext"]);

/* These two are written into styles.css as data: URIs rather than linked.

   A linked font cannot be there for the very first paint, and every way of
   handling that gap is wrong here: block hides the text and then reveals it
   (the blink), swap paints a fallback and then replaces it (the re-layout),
   and optional was measured committing to the fallback for the whole page
   load. A preload closes the gap over https but is ignored over file://, and
   this site is opened both ways — by double-clicking the HTML, and from
   Cloudflare Pages.

   In the stylesheet there is no gap. styles.css is render-blocking, so by the
   time anything is painted the font is already there: no wait, no swap, no
   fallback, in either environment.

   It costs about 120 kB of base64 in a render-blocking file, which is why it
   is these two and not all six. They are the roman latin faces — every word of
   the nav, the mastheads and the menus. The other four are italics and
   extended characters, are rarely on screen, and stay linked. */
const CRITICAL = new Set(["fraunces-roman-latin.woff2", "manrope-roman-latin.woff2"]);

const DIR = "assets/fonts";
const START = "/* ── self-hosted webfonts — generated by tools/fetch-fonts.mjs ── */";
const END = "/* ── end generated webfonts ── */";

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

/* Each face is preceded by a comment naming its subset. */
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
  .map(([, subset, body]) => ({ subset, body }))
  .filter((b) => SUBSETS.has(b.subset));

if (!blocks.length) throw new Error("no font faces matched — has the CSS format changed?");

mkdirSync(DIR, { recursive: true });

/* Google emits one @font-face per weight asked for, and every one of them
   points at the same file — these are variable fonts, so a single face
   carrying the whole weight range is exactly equivalent. Collapsing them is
   tidier on its own, and load-bearing once a face is inlined: without it the
   same 88 kB of base64 is written into the stylesheet five times over, which
   is how the first attempt produced a 626 kB styles.css. */
const faces = new Map();
for (const { subset, body } of blocks) {
  const url = body.match(/url\((https:[^)]+)\)/)[1];
  const style = /font-style:\s*italic/.test(body) ? "italic" : "roman";
  const weight = Number(body.match(/font-weight:\s*(\d+)/)[1]);
  const face = faces.get(url) || { subset, style, body, weights: [] };
  face.weights.push(weight);
  faces.set(url, face);
}

const seen = new Map();
let out = [];

for (const [url, { subset, style, body, weights }] of faces) {
  const family = body.match(/font-family:\s*'([^']+)'/)[1].toLowerCase();
  const range = `${Math.min(...weights)} ${Math.max(...weights)}`;

  let asset = seen.get(url);
  if (!asset) {
    /* No weight in the name: these are variable fonts, so one file serves
       every weight in the family and several faces point at it. */
    const file = `${family}-${style}-${subset}.woff2`;
    const res = await fetch(url, { headers: { "User-Agent": UA } });
    if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`);
    const bytes = Buffer.from(await res.arrayBuffer());
    writeFileSync(`${DIR}/${file}`, bytes);

    /* CRITICAL faces go into the stylesheet as data: URIs; everything else
       stays a file. See the note on CRITICAL above. */
    const inline = CRITICAL.has(file);
    asset = {
      file,
      css: inline
        ? `url(data:font/woff2;base64,${bytes.toString("base64")})`
        : `url(${DIR}/${file})`,
      inline,
      kb: bytes.length / 1024
    };
    seen.set(url, asset);
    console.log(`  ${inline ? "inlined " : "file    "} ${file.padEnd(34)} ${asset.kb.toFixed(1)} kB`);
  }

  /* font-display, and only for the faces that are still files.

     An inlined face must NOT carry `optional`, which is not the same as the
     descriptor being irrelevant to it — that assumption was tried and was
     wrong. `optional` decides at the first render opportunity, and the font
     loading pipeline has not finished by then even for a data: URI, so it
     commits to the fallback and stays there for the whole page load: the nav
     measured 121.91px instead of Fraunces' 119.08px. With no descriptor the
     browser waits instead, and for a data: URI there is nothing to wait for.

       auto / block  hides the text until the font loads, then shows it — a
                     blink on every page. This is what dropping the descriptor
                     gave, and it is what this is fixing.
       swap          paints a fallback and replaces it, which is the re-layout
                     that self-hosting exists to end.
       optional      commits to whatever is ready at the first paint and never
                     swaps. Measured over file://, where a crossorigin preload
                     is ignored, that meant committing to the fallback and
                     staying there: the nav rendered at the fallback's 121.91px
                     instead of Fraunces' 119.08px, for the whole page load.

     So `optional` for the rest: never swapping is the property worth keeping,
     and these faces carry italics and extended characters that are rarely on
     screen at all. The text that is always on screen does not depend on it —
     it is in the stylesheet already. */
  out.push(
    body
      .replace(/url\(https:[^)]+\)/, asset.css)
      .replace(/font-weight:\s*\d+;/, `font-weight: ${range};`)
      .replace(/font-display:[^;]+;/, asset.inline ? "" : "font-display: optional;")
      .replace(/^@font-face\s*\{/, `/* ${subset}${asset.inline ? ", inlined" : ""} */\n@font-face{`)
      .replace(/\n\s+/g, "\n  ")
  );
}

const generated = [START, ...out, END].join("\n");

const sheet = readFileSync("styles.css", "utf8");
const s = sheet.indexOf(START);
const e = sheet.indexOf(END);
if (s < 0 || e < 0) throw new Error("markers not found in styles.css");

writeFileSync("styles.css", sheet.slice(0, s) + generated + sheet.slice(e + END.length));
console.log(`\n${seen.size} files in ${DIR}, ${out.length} faces written into styles.css`);
