/* Bring the webfonts into the repo, so the browser never has to swap them in.
   node tools/fetch-fonts.mjs

   Why this exists. The fonts were loaded from Google, which means the first
   paint of every page uses a fallback face and the real one replaces it a
   moment later. Text measured in the fallback is a slightly different width, so
   the page re-lays-out under the visitor: the wordmark in the nav moved 2.83px
   and the Menus button 1.88px on every navigation, and on the menu pages a
   re-wrapped lede moved the masthead's bottom edge — a hard colour seam across
   the whole page — by 31.5px.

   styles.css already carries metric-matched fallback faces to shrink that gap,
   and they took it from roughly 12px down to under 3px. Under 3px is still
   visible on a fixed bar you see on every page, and no amount of further
   tuning reaches zero, because size-adjust is one ratio for a whole face while
   individual letters differ. The only way to zero is for there to be no swap.

   Self-hosted and preloaded, the font is requested alongside the stylesheet
   from the same origin and is normally in place for the first paint. It also
   matches what this project already does everywhere else: admin.html loads the
   Supabase SDK from vendor/, never a CDN. The fonts were the last exception.

   Both families are SIL Open Font License, which permits this. The licence is
   written next to the files.

   Re-run this if the font stack in the page ever changes. It rewrites the
   block between the markers in styles.css and nothing else. */

import { writeFileSync, readFileSync, mkdirSync } from "node:fs";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,300;1,9..144,400" +
  "&family=Manrope:wght@300;400;500;600;700&display=swap";

/* A modern browser's UA, or Google serves the old truetype CSS instead of the
   variable woff2 one. */
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
           "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

/* The site is English with a few accented characters — Café, crêpe, the
   Georgian dish names in Latin transliteration. latin and latin-ext cover all
   of it. Cyrillic, Greek and Vietnamese are dropped: the browser would never
   request them, and they are files someone has to drag onto Cloudflare. */
const SUBSETS = new Set(["latin", "latin-ext"]);

const DIR = "assets/fonts";
const START = "/* ── self-hosted webfonts — generated by tools/fetch-fonts.mjs ── */";
const END = "/* ── end generated webfonts ── */";

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

/* Each face is preceded by a comment naming its subset. */
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
  .map(([, subset, body]) => ({ subset, body }))
  .filter((b) => SUBSETS.has(b.subset));

if (!blocks.length) throw new Error("no font faces matched — has the CSS format changed?");

mkdirSync(DIR, { recursive: true });

const seen = new Map();
let out = [];

for (const { subset, body } of blocks) {
  const url = body.match(/url\((https:[^)]+)\)/)[1];
  const family = body.match(/font-family:\s*'([^']+)'/)[1].toLowerCase();
  const style = /font-style:\s*italic/.test(body) ? "italic" : "roman";
  const weight = body.match(/font-weight:\s*([^;]+);/)[1].trim().replace(/\s+/g, "-");

  let file = seen.get(url);
  if (!file) {
    /* No weight in the name: these are variable fonts, so one file serves
       every weight in the family and several faces point at it. */
    file = `${family}-${style}-${subset}.woff2`;
    const res = await fetch(url, { headers: { "User-Agent": UA } });
    if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`);
    const bytes = Buffer.from(await res.arrayBuffer());
    writeFileSync(`${DIR}/${file}`, bytes);
    seen.set(url, file);
    console.log(`  ${file}  ${(bytes.length / 1024).toFixed(1)} kB`);
  }

  /* font-display is dropped on purpose. The point of self-hosting is that the
     font is there for the first paint; `swap` would only describe what happens
     when it is not, and the default (`auto`) lets the browser block briefly
     rather than paint a fallback it will have to replace. */
  out.push(
    body
      .replace(/url\(https:[^)]+\)/, `url(${DIR}/${file})`)
      .replace(/\s*font-display:[^;]+;/, "")
      .replace(/^@font-face\s*\{/, `/* ${subset} */\n@font-face{`)
      .replace(/\n\s+/g, "\n  ")
  );
}

const generated = [START, ...out, END].join("\n");

const sheet = readFileSync("styles.css", "utf8");
const s = sheet.indexOf(START);
const e = sheet.indexOf(END);
if (s < 0 || e < 0) throw new Error("markers not found in styles.css");

writeFileSync("styles.css", sheet.slice(0, s) + generated + sheet.slice(e + END.length));
console.log(`\n${seen.size} files in ${DIR}, ${out.length} faces written into styles.css`);
