-- ============================================================================
-- Aromati — content seed
--
-- GENERATED by tools/gen-seed-sql.mjs from data/seed-*.js. Do not hand-edit:
-- the next run overwrites it, and the site would keep the old values anyway.
-- To change something here, change the seed data and run the generator.
--
-- 17 sections, 84 items, 26 pours, 7 options, 62 copy fields.
--
-- Runs once, at Phase 3 step 6. The ids are derived from each row's position
-- in the seed data rather than generated, so this file is stable in a diff --
-- but it also means re-running it after reordering the menu would collide.
-- If it has to be applied twice, empty the tables first.
--
-- Not seeded here: the FAQ (18 entries, held pending the owner's answer on
-- the demo notice) and the photos (Phase 6 defines the slots).
-- ============================================================================

-- ---- sections --------------------------------------------------------------
insert into public.menu_courses (id, page, course_key, tab_label, heading, sizes, is_static, static_id, sort_order) values
  ('576a34df-e289-59ab-96e2-071d80bdd432', 'food', 'breakfast', 'Breakfast', 'Breakfast', null, false, null, 1),
  ('8ab2cabd-6099-5a61-9042-457adc096c8e', 'food', 'appetizers', 'Appetizers', 'Appetizers', null, false, null, 2),
  ('37a80aea-cf89-5030-aeed-123716f679a8', 'food', 'mains', 'Khachapuri & Breads', 'Main Georgian Dishes', null, false, null, 3),
  ('f00ce704-100e-5c30-821b-bc775899ed8d', 'food', 'hot', 'Hot Dishes', 'Hot Dishes', null, false, null, 4),
  ('0c5e8156-4ca2-527d-8aa3-0bb0f42e8624', 'food', 'soups', 'Soups', 'Soups', null, false, null, 5),
  ('f810779f-a24c-5109-80a5-f89b5dabdffe', 'food', 'desserts', 'Desserts', 'Desserts', null, false, null, 6),
  ('822e8a10-9920-5198-89fa-99230f6436ca', 'food', 'breakfast', 'Breakfast', 'Build Your Own Breakfast', null, true, 'build', 7),
  ('3f25979d-74ad-5683-81de-f9b15afde2f5', 'drinks', 'coffee', 'Coffee', 'Coffee & Espresso', array['Small', 'Large'], false, null, 1),
  ('76ed7f14-0dfb-5da8-a741-64f27822d3da', 'drinks', 'tea', 'Tea & Matcha', 'Tea, Matcha & Cocoa', array['Small', 'Large'], false, null, 2),
  ('77c630ff-f21d-573f-bc56-d63f59cda03b', 'drinks', 'smoothies', 'Smoothies', 'Smoothies', null, false, null, 3),
  ('bc477256-00ab-54e9-a645-f20d237bdf41', 'drinks', 'cold', 'Cold Beverages', 'Cold Beverages', null, false, null, 4),
  ('ef721aad-8ca3-5c7e-aecc-f33a25579e58', 'wine', 'cocktails', 'Cocktails', 'Cocktails', null, false, null, 1),
  ('baa440a4-62dd-5745-a0f4-0a41110a01f8', 'wine', 'white', 'Georgian White', 'Georgian White Wine', null, false, null, 2),
  ('be178dde-3b22-53d9-a88e-9aea7042eb22', 'wine', 'natural', 'Natural', 'Georgian Natural Wine', null, false, null, 3),
  ('c1c26fc2-cf3e-573f-b09e-ca13e4924f79', 'wine', 'red', 'Georgian Red', 'Georgian Red Wine', null, false, null, 4),
  ('b4b87b25-b782-523d-8ccf-4fcb26e58921', 'wine', 'european', 'European', 'European Wine & Spirits', null, false, null, 5),
  ('7e57b1ba-3e8d-5b12-b7ef-5356da011928', 'wine', 'boards', 'Pairings', 'Wine Pairings', null, false, null, 6);

-- ---- items -----------------------------------------------------------------
-- Prices are text, never numeric: 3.90 stored as a number renders as 3.9.
insert into public.menu_items (id, course_id, name, tag, description, price, prices, price_all_sizes, no_price, options_dom_id, sort_order) values
  ('441a99d9-73f3-56ee-8f28-9f7909a26d0f', '576a34df-e289-59ab-96e2-071d80bdd432', 'Morning Plate', null, 'Mixed greens with scrambled eggs, avocado, sour cream and toasted sourdough. Choice of cured meats or smoked salmon.', '21', null, null, false, null, 1),
  ('63559f33-73c6-53b7-89f3-232db61cff93', '576a34df-e289-59ab-96e2-071d80bdd432', 'Shakshuka', null, 'Poached eggs in a rich tomato and bell pepper sauce, finished with garlic, paprika and fresh herbs. Served with warm toasted sourdough.', '16', null, null, false, null, 2),
  ('d9056592-c497-5b97-9e36-b29532d34f68', '576a34df-e289-59ab-96e2-071d80bdd432', 'Breakfast Board for Two', null, 'A fresh mixed greens salad with scrambled eggs, avocado and olives, served with toasted sourdough, cream cheese, house-made sauce, jam and a dairy sweet. Choice of cured meats or smoked salmon.', '39', null, null, false, null, 3),
  ('58f9049f-8ceb-51d4-ae73-1ffb996a3fb2', '8ab2cabd-6099-5a61-9042-457adc096c8e', 'Assorted Pkhali', null, 'Georgian vegetable and eggplant rolls with walnut and Georgian spices, with homemade cornbread or bread.', '21', null, null, false, null, 1),
  ('6e51eb3c-0580-545c-aa8a-981d25f4cc2a', '8ab2cabd-6099-5a61-9042-457adc096c8e', 'Aromati’s Mix Salad', null, 'Fresh mixed greens with tomatoes, cucumbers, walnuts and herbs, finished with a house-made dressing.', '17', null, null, false, null, 2),
  ('6729105f-aacd-5ffa-8fd4-2ee8394a497c', '8ab2cabd-6099-5a61-9042-457adc096c8e', 'Eggplant Rolls', null, 'Roasted eggplant filled with garlic-walnut sauce, topped with pomegranate.', '18', null, null, false, null, 3),
  ('a92b49e5-0ef2-5204-b8c1-c2cb4594f12d', '8ab2cabd-6099-5a61-9042-457adc096c8e', 'Arugula Salad with Goat Cheese', null, 'A fresh blend of arugula, strawberries, garlic and herbs, finished with oil and house-made dressing.', '19', null, null, false, null, 4),
  ('9097c6c3-49d0-5de6-b353-8226463f04a6', '8ab2cabd-6099-5a61-9042-457adc096c8e', 'The Georgian Salad', null, 'Tomatoes, cucumbers, onions, herbs and walnuts tossed in traditional sunflower oil and vinegar dressing.', '17', null, null, false, null, 5),
  ('d5ed13b4-aa88-51dc-acde-b6dc611f6aba', '37a80aea-cf89-5030-aeed-123716f679a8', 'Penovani Khachapuri', null, 'Puff pastry stuffed with blended cheese.', '15', null, null, false, null, 1),
  ('3aba55a7-d4e3-5758-9882-382459a4ff05', '37a80aea-cf89-5030-aeed-123716f679a8', 'Imeruli Khachapuri', null, 'Round-shaped khachapuri with a cheese filling.', '19', null, null, false, null, 2),
  ('68bb88ae-812d-5cd9-b922-03307b8098b5', '37a80aea-cf89-5030-aeed-123716f679a8', 'Adjaruli Khachapuri', null, 'A boat-shaped khachapuri with cheese, topped with an egg yolk and butter.', '19', null, null, false, null, 3),
  ('3035c090-5738-5d99-a99d-dcacb95640d8', '37a80aea-cf89-5030-aeed-123716f679a8', 'Lobiani', null, 'Traditional bean-filled homemade bread.', '17', null, null, false, null, 4),
  ('a20350a8-4325-5388-8a53-9273ffdbd2e0', 'f00ce704-100e-5c30-821b-bc775899ed8d', 'Georgian Dumplings — Khinkali', null, 'Hand-folded Georgian dumplings in a flavorful, savory broth. Three per serving.', '14', null, null, false, null, 1),
  ('a37f1429-031f-5e71-a7a2-64ea3289514a', 'f00ce704-100e-5c30-821b-bc775899ed8d', 'Tolma', null, 'Seasoned ground beef wrapped in grape leaves, served with creamy homemade yogurt and garlic sour cream. Five pieces.', '16', null, null, false, null, 2),
  ('c8db0960-e972-5199-bbbd-ce7df764265e', 'f00ce704-100e-5c30-821b-bc775899ed8d', 'Kvarabia', null, 'Megruli cheese dumplings, served with homemade yogurt. Three per serving.', '12', null, null, false, null, 3),
  ('4faa6eea-512d-5aa5-9913-a613f4cff052', '0c5e8156-4ca2-527d-8aa3-0bb0f42e8624', 'Tomato Cream Soup', null, 'A delicious medley of tomatoes, light cream, spices and garlic.', '14', null, null, false, null, 1),
  ('7943ffa1-1830-5a23-b4e5-e10d35f50142', '0c5e8156-4ca2-527d-8aa3-0bb0f42e8624', 'Matsoni Soup', null, 'Georgian matsoni — a traditional yogurt similar to Greek — with rice, sour cream, eggs, onions, parsley, coriander, scallions and mint.', '14', null, null, false, null, 2),
  ('6f66e88d-3b44-5f47-9b89-0ad2907b02f2', '0c5e8156-4ca2-527d-8aa3-0bb0f42e8624', 'Broccoli & Cheddar Soup', null, 'Generous pieces of broccoli, creamy sharp cheddar and a touch of spice.', '14', null, null, false, null, 3),
  ('55f33766-c2d6-5e8d-a0e3-a83d8a10585d', 'f810779f-a24c-5109-80a5-f89b5dabdffe', 'Aromati’s Signature Cheesecake', null, null, '13', null, null, false, null, 1),
  ('0d686b14-a3a4-5756-959e-e0ac0fe0fdf0', 'f810779f-a24c-5109-80a5-f89b5dabdffe', 'Chimney Cake', null, 'Filled with white chocolate or Nutella cream, served with ice cream and your choice of fresh fruits.', '12', null, null, false, null, 2),
  ('881dd11d-cb34-5f64-8be6-4a4c3f9c606c', 'f810779f-a24c-5109-80a5-f89b5dabdffe', 'Aromati’s Classic Brownie', null, 'Served with ice cream and topped with walnuts.', '11', null, null, false, null, 3),
  ('fbc85f76-b6a3-5dd3-bd4a-6eb27058239d', 'f810779f-a24c-5109-80a5-f89b5dabdffe', 'Pelamushi', null, 'Traditional Georgian grape pudding.', '12', null, null, false, null, 4),
  ('938d78a6-9232-5e94-b1b0-e4a2d31e4e0a', 'f810779f-a24c-5109-80a5-f89b5dabdffe', 'Warm Chocolate Molten Lava Cake', null, 'Paired with vanilla ice cream and fresh strawberry.', '13', null, null, false, null, 5),
  ('d02f267a-a10b-54d2-b7d9-f950989eb661', 'f810779f-a24c-5109-80a5-f89b5dabdffe', 'Cheesecake', null, 'Topped with melted chocolate and finished with blended pistachios.', '13', null, null, false, null, 6),
  ('4be780a0-a50d-5aea-976a-d48f12dc8e96', 'f810779f-a24c-5109-80a5-f89b5dabdffe', 'Aromati’s Crêpe', '7 toppings', 'Made to order. Dress it however you like.', '5', null, null, false, 'crepeOpts', 7),
  ('027e2df7-7436-5312-b818-46f3715c2eba', '3f25979d-74ad-5683-81de-f9b15afde2f5', 'Espresso', null, null, null, null, '3', false, null, 1),
  ('52b70258-d171-54ca-a060-1049921aec95', '3f25979d-74ad-5683-81de-f9b15afde2f5', 'Americano', null, null, null, null, '4', false, null, 2),
  ('d2ae3847-e2ad-5870-8fb0-be0f2b2466f4', '3f25979d-74ad-5683-81de-f9b15afde2f5', 'Cortado', null, null, null, null, '4', false, null, 3),
  ('a072a7af-6038-5a6d-84b5-4d778de51cfc', '3f25979d-74ad-5683-81de-f9b15afde2f5', 'Drip Coffee', null, 'Fresh pot, all morning.', null, '["4","5"]'::jsonb, null, false, null, 4),
  ('5940a0ac-492d-57b5-903a-7d9a80559211', '3f25979d-74ad-5683-81de-f9b15afde2f5', 'Cold Brew', null, 'Slow-steeped, served over ice.', null, '["5","6"]'::jsonb, null, false, null, 5),
  ('be8cdf0d-9393-54ef-9f1b-c6f14fe2f9f8', '3f25979d-74ad-5683-81de-f9b15afde2f5', 'Cappuccino', null, null, null, '["5","6"]'::jsonb, null, false, null, 6),
  ('c6ab84fe-07c6-5215-96ec-b8ae33ad036a', '3f25979d-74ad-5683-81de-f9b15afde2f5', 'Latte', null, null, null, '["6","7"]'::jsonb, null, false, null, 7),
  ('68477753-13dc-526d-90db-1b4eb0febbee', '3f25979d-74ad-5683-81de-f9b15afde2f5', 'Iced Latte', null, null, null, '["6","7"]'::jsonb, null, false, null, 8),
  ('4b1b6216-abba-5f7f-bbb5-661763cbad07', '3f25979d-74ad-5683-81de-f9b15afde2f5', 'Mocha Latte', null, null, null, '["6","7"]'::jsonb, null, false, null, 9),
  ('3b6f108f-91b8-5cee-be01-f400ed5f6d3e', '76ed7f14-0dfb-5da8-a741-64f27822d3da', 'Matcha Latte', null, null, null, '["6","7"]'::jsonb, null, false, null, 1),
  ('34832b7a-25d3-5d0d-bec6-4f873350707e', '76ed7f14-0dfb-5da8-a741-64f27822d3da', 'Strawberry Matcha', null, null, null, '["7","8"]'::jsonb, null, false, null, 2),
  ('2914d06b-13e4-5453-aaa8-9a242d16e4ce', '76ed7f14-0dfb-5da8-a741-64f27822d3da', 'Chai Latte', null, null, null, '["6","7"]'::jsonb, null, false, null, 3),
  ('fc8d5b47-a8d7-5918-995b-2171090d1a1b', '76ed7f14-0dfb-5da8-a741-64f27822d3da', 'Turmeric Latte', null, null, null, '["7","8"]'::jsonb, null, false, null, 4),
  ('f19893a1-cd62-5a18-9891-4fd71e9f768a', '76ed7f14-0dfb-5da8-a741-64f27822d3da', 'Hot Chocolate', null, null, null, '["5","6"]'::jsonb, null, false, null, 5),
  ('e32991f3-bba0-5715-9d27-9854c199543b', '76ed7f14-0dfb-5da8-a741-64f27822d3da', 'Hot Tea', null, 'Different flavors — ask at the counter.', null, '["3","4"]'::jsonb, null, false, null, 6),
  ('50880e73-da9e-5e6e-82be-fa5e21d046e9', '76ed7f14-0dfb-5da8-a741-64f27822d3da', 'Iced Tea', null, 'Passion fruit and regular.', null, '["4","5"]'::jsonb, null, false, null, 7),
  ('d0733c09-e427-5aaf-b2af-1565b1f3c9e1', '77c630ff-f21d-573f-bc56-d63f59cda03b', 'Grape Harmony', null, 'Smucker’s Squeeze grape jelly, banana, blueberry and zero-sugar grape juice, mixed with hazelnut.', '12', null, null, false, null, 1),
  ('f67e2666-f44d-55ac-86be-f6a4c7d4ad1d', '77c630ff-f21d-573f-bc56-d63f59cda03b', 'Blush Velvet', null, 'Almond milk, strawberry, banana, date, coconut cream and coconut flakes.', '12', null, null, false, null, 2),
  ('6e95bdef-591c-5144-93f4-a58d52ed5bfe', '77c630ff-f21d-573f-bc56-d63f59cda03b', 'Green Glow', null, 'Coconut water, spinach, ginger, pineapple and cucumber.', '12', null, null, false, null, 3),
  ('442da8c5-26c4-56f5-8a1b-3592be1f2ae5', '77c630ff-f21d-573f-bc56-d63f59cda03b', 'Wake Me Up', null, 'Almond milk, banana, espresso, cacao nibs, cocoa powder and protein.', '12', null, null, false, null, 4),
  ('6561da9a-329a-5477-a936-99acabb036d9', 'bc477256-00ab-54e9-a645-f20d237bdf41', 'Saratoga Still Water', null, null, '2.50', null, null, false, null, 1),
  ('ec267269-cd64-5e64-8f40-8eb235d537c6', 'bc477256-00ab-54e9-a645-f20d237bdf41', 'Classic Coke', null, null, '3', null, null, false, null, 2),
  ('51ee34c5-c88d-5e4a-8c3a-5248f02658e2', 'bc477256-00ab-54e9-a645-f20d237bdf41', 'Diet Coke', null, null, '3', null, null, false, null, 3),
  ('fac94b95-10e3-51dd-910a-92681b610237', 'bc477256-00ab-54e9-a645-f20d237bdf41', 'Natural Lemonade', null, null, '4.50', null, null, false, null, 4),
  ('ff0fff63-1dce-51f6-8164-6f9f47f360f6', 'bc477256-00ab-54e9-a645-f20d237bdf41', 'Orange Juice', null, null, '4.50', null, null, false, null, 5),
  ('f9ae30ca-7957-56af-aa98-4ea180f26d63', 'bc477256-00ab-54e9-a645-f20d237bdf41', 'Georgian Lemonade', null, 'Tarragon · Pear · Lemon.', '5', null, null, false, null, 6),
  ('e0b0aed6-19e1-5af4-abaa-4a7f82aec849', 'bc477256-00ab-54e9-a645-f20d237bdf41', 'S.Pellegrino Sparkling Water', '750 ml', null, '7', null, null, false, null, 7),
  ('f4107a76-5ba7-5191-82c9-9259d49cf947', 'bc477256-00ab-54e9-a645-f20d237bdf41', 'Borjomi Sparkling Water', '750 ml', 'The Georgian mineral water, straight from Borjomi.', '7.50', null, null, false, null, 8),
  ('5ebf411d-aa7c-53a7-bd1f-7ed3b9094189', 'ef721aad-8ca3-5c7e-aecc-f33a25579e58', 'Classic Aperol Spritz', null, 'Aperol, prosecco, fresh orange.', '17', null, null, false, null, 1),
  ('faf6820a-a4c6-5094-a628-7642cedf70a6', 'ef721aad-8ca3-5c7e-aecc-f33a25579e58', 'Aromati’s Limoncello Spritz', null, 'Prosecco Brut DOC, Amalfi Coast organic limoncello, dry lemon garnish.', '18', null, null, false, null, 2),
  ('17a8efbe-ffe1-5db9-ba2a-619c9a6d0044', 'ef721aad-8ca3-5c7e-aecc-f33a25579e58', 'Pomegranate Spritz', null, 'Aperol, prosecco, pomegranate juice.', '17', null, null, false, null, 3),
  ('5506e480-8329-5923-a9be-fb51747613ff', 'ef721aad-8ca3-5c7e-aecc-f33a25579e58', 'Sparkling Grape Cocktail', null, 'Sparkling wine, Prosecco Brut DOC, grape juice, lime.', '17', null, null, false, null, 4),
  ('3147a50f-7b7a-5945-831a-bd776470c05a', 'ef721aad-8ca3-5c7e-aecc-f33a25579e58', 'Mint Mojito', null, 'Sparkling wine, fresh mint, lime.', '14', null, null, false, null, 5),
  ('93b47bdb-e726-5b41-b262-1c1c85f0af0d', 'baa440a4-62dd-5745-a0f4-0a41110a01f8', 'Pirosmani White', null, 'Table wine, Kakheti — balanced and fruity, with notes of ripe white fruit, pear, melon and citrus.', '15', null, null, false, null, 1),
  ('9ac05b54-2cf3-542a-bc7b-80e7331795d8', 'baa440a4-62dd-5745-a0f4-0a41110a01f8', 'Rkatsiteli Qvevri', null, 'Dry amber qvevri wine, Kakheti — pronounced spicy aromas with hints of honey and tobacco.', '17', null, null, false, null, 2),
  ('c534ae8b-033e-5755-b467-019643c89532', 'baa440a4-62dd-5745-a0f4-0a41110a01f8', 'Kisi Qvevri', null, 'Dry amber qvevri wine, Kakheti — honey and cinnamon aromas with notes of yellow and dried fruits.', '17', null, null, false, null, 3),
  ('3f613a0a-108b-51a3-9df5-c3e2067c6ef3', 'baa440a4-62dd-5745-a0f4-0a41110a01f8', 'Tsolikouri', null, 'Imereti dry white wine, with delicate aromas of yellow and white fruits.', '16', null, null, false, null, 4),
  ('d85c7d47-5304-5b75-94b3-68003c3e8bb6', 'baa440a4-62dd-5745-a0f4-0a41110a01f8', 'Tvishi', null, 'Naturally semi-sweet, Lechkhumi — yellow and tropical fruit aromas with citrus undertones.', '16', null, null, false, null, 5),
  ('270cf64b-0554-50de-bc0c-944a1bbb1a75', 'baa440a4-62dd-5745-a0f4-0a41110a01f8', 'Brut', null, 'Sparkling wine, Imereti · Kakheti · Kartli — pale straw, high acidity, notes of citrus, pear and stone fruit.', '15', null, null, false, null, 6),
  ('1b29ba10-a0ba-5dc1-8bba-45fcced4249e', 'be178dde-3b22-53d9-a88e-9aea7042eb22', 'Mtsvane', '2022', 'Single vineyard Kakheti, Manavi Wines. Dry white with crisp green apple, juicy pear and delicate floral notes.', '16', null, null, false, null, 1),
  ('c5007111-3974-53e6-80c4-39f0a1ef670e', 'be178dde-3b22-53d9-a88e-9aea7042eb22', 'Rkatsiteli', '2023', 'Khvitsia Wine, Kardenakhi — Kakheti. Dry white with lively acidity and floral hints.', '17', null, null, false, null, 2),
  ('e73844af-e931-5453-a9d6-ee52b72c070b', 'be178dde-3b22-53d9-a88e-9aea7042eb22', 'Kisi', '2020', 'Kakheti, Vellino. Dry amber with ripe apricot and peach, floral hints and a touch of citrus.', '18', null, null, false, null, 3),
  ('37498d05-4bed-593a-91ae-aa4fef1c0f30', 'be178dde-3b22-53d9-a88e-9aea7042eb22', 'Mtsvane', '2020', 'Kakheti. Dry amber with primary aromas of lemon, lime and green apple, with notes of tropical fruit.', '17', null, null, false, null, 4),
  ('e74e1da5-2c45-5a8d-a6cd-af44c58f3356', 'be178dde-3b22-53d9-a88e-9aea7042eb22', 'Saperavi', '2023', 'Nadelebi Winery, Kakheti. Dry red, rich with dark berries — black cherry and blackberry, with hints of plum and florals.', '18', null, null, false, null, 5),
  ('b2bd7d94-d683-590f-afc3-77b2f4ca5f15', 'be178dde-3b22-53d9-a88e-9aea7042eb22', 'Sopromadze', '2022', 'Tsitska · Tsolikouri · Krakhuna, Kakheti. Dry white with crisp acidity and fresh citrus notes.', '18', null, null, false, null, 6),
  ('e70c24f8-40ff-5fc9-97bb-517761e1e271', 'c1c26fc2-cf3e-573f-b09e-ca13e4924f79', 'Saperavi Qvevri', null, 'Dry red qvevri wine from Kakheti — aromas of dried black plum, cherry and blackberry.', '17', null, null, false, null, 1),
  ('c9e658e9-19e6-570b-b390-7abc91b15d06', 'c1c26fc2-cf3e-573f-b09e-ca13e4924f79', 'Saperavi Reserve', null, 'Premium red, Kakheti — plum, blackberry and cherry with spice and vanilla, aged in oak for a velvety finish.', '18', null, null, false, null, 2),
  ('5058412e-97c4-57a9-95f6-2674156958ac', 'c1c26fc2-cf3e-573f-b09e-ca13e4924f79', 'Kindzmarauli', null, 'Semi-sweet red, with a rich flavor of berries, plum and rose petals.', '18', null, null, false, null, 3),
  ('d4191b99-3e5d-5d98-97ec-827e7d7e8a05', 'c1c26fc2-cf3e-573f-b09e-ca13e4924f79', 'Mukuzani', null, 'Dry red from Kakheti — rich dark berry aromas with hints of oak and spice.', '18', null, null, false, null, 4),
  ('265d561e-23d3-52cc-9da9-e7e2f195c8c1', 'b4b87b25-b782-523d-8ccf-4fcb26e58921', 'Barbera d’Asti', null, 'Piedmont — rich with floral tones of iris and rose, with hints of undergrowth, raspberry and plum.', '15', null, null, false, null, 1),
  ('e4175bd7-9ec9-57f1-b2ef-a6825d42776d', 'b4b87b25-b782-523d-8ccf-4fcb26e58921', 'Friularo', null, 'An elegant red with an intense aroma, featuring spicy notes, violet and sour cherry.', '17', null, null, false, null, 2),
  ('541f1c3f-13ab-5d10-968e-53bfe11a2ac3', 'b4b87b25-b782-523d-8ccf-4fcb26e58921', 'Sauvignon Blanc', null, 'Elegant and balanced, crisp acidity and flowers on the nose, with white peach, grapefruit, tropical fruit and citrus.', '18', null, null, false, null, 3),
  ('738eb521-0f4c-566e-bd43-585454bee99d', 'b4b87b25-b782-523d-8ccf-4fcb26e58921', 'Falanghina del Sannio', null, 'Aromatic notes of ripe apple and citrus blossom, hints of pear, peach and crushed stone, crisp with a refreshing structure.', '18', null, null, false, null, 4),
  ('2cd251f2-db1e-5798-b17c-45581ad38b22', 'b4b87b25-b782-523d-8ccf-4fcb26e58921', 'Chardonnay', null, 'Structured and fresh, with hints of apricot and green apple — intense and refined, with a robust finish.', '18', null, null, false, null, 5),
  ('93148e6b-02bf-5bfc-bc9b-5a2ba590589b', 'b4b87b25-b782-523d-8ccf-4fcb26e58921', 'Prosecco Brut', null, 'Very fine and elegant, floral and fruity, with hints of acacia flower, green apple and almond. Dry, fresh, lively on the palate.', '16', null, null, false, null, 6),
  ('9362922a-0e16-56ea-9df2-da761f7c03c5', 'b4b87b25-b782-523d-8ccf-4fcb26e58921', 'Corona Extra', '12 oz', null, '6.50', null, null, false, null, 7),
  ('a9437669-db42-5f3b-9ef4-3a27a23d2e09', 'b4b87b25-b782-523d-8ccf-4fcb26e58921', 'Heineken', '12 oz', null, '6', null, null, false, null, 8),
  ('db5c44d1-763a-58db-b03a-d63fac16ef36', '7e57b1ba-3e8d-5b12-b7ef-5356da011928', 'Aromati’s Charcuterie & Cheese Board', null, 'A selection of cured meats and artisan cheeses, served with fresh fruit, olives, nuts, jam and crackers.', null, null, null, true, null, 1),
  ('dcd8297f-a8b5-50b4-9a6b-aa99c25d4b19', '7e57b1ba-3e8d-5b12-b7ef-5356da011928', 'Cheese Board', null, 'Chef’s selection of artisan cheeses, served with croutons, fresh fruit, nuts and jam.', null, null, null, true, null, 2);

-- ---- pours (the "Bottle $60" lines) -----------------------------------------
insert into public.menu_item_pours (id, item_id, label, price, sort_order) values
  ('7ff0e208-eb5c-5bc2-9b9a-4287a17d16be', '93b47bdb-e726-5b41-b262-1c1c85f0af0d', 'Bottle', '60', 1),
  ('ec1b8460-c0a9-5111-9e18-314cc8725724', '9ac05b54-2cf3-542a-bc7b-80e7331795d8', 'Bottle', '70', 1),
  ('3443b0ab-48f7-5560-b3a6-5dbe67629b6b', 'c534ae8b-033e-5755-b467-019643c89532', 'Bottle', '70', 1),
  ('7464d0e2-969a-553c-be72-8978997a548a', '3f613a0a-108b-51a3-9df5-c3e2067c6ef3', 'Bottle', '65', 1),
  ('50707dec-9890-5222-bb9e-89e11e7c4c1b', 'd85c7d47-5304-5b75-94b3-68003c3e8bb6', 'Bottle', '65', 1),
  ('80364af2-22b3-5df9-b602-227477816717', '270cf64b-0554-50de-bc0c-944a1bbb1a75', 'Bottle', '60', 1),
  ('fc5880bd-ea56-5a55-b20d-0426e69a74aa', '1b29ba10-a0ba-5dc1-8bba-45fcced4249e', 'Bottle', '64', 1),
  ('6afebc07-fccf-5989-a628-85ee6f86846a', 'c5007111-3974-53e6-80c4-39f0a1ef670e', 'Bottle', '68', 1),
  ('7c5af8ee-5e65-5386-a052-240922ca58d0', 'e73844af-e931-5453-a9d6-ee52b72c070b', 'Bottle', '72', 1),
  ('bc04a228-fc6e-5bfa-873b-f159af34efe5', '37498d05-4bed-593a-91ae-aa4fef1c0f30', 'Bottle', '68', 1),
  ('3d206646-673d-5da3-b43b-862fcbddbaba', 'e74e1da5-2c45-5a8d-a6cd-af44c58f3356', 'Bottle', '72', 1),
  ('e26ca001-4658-5a68-b135-0cecd1a4b8d8', 'b2bd7d94-d683-590f-afc3-77b2f4ca5f15', 'Bottle', '72', 1),
  ('5dd92abe-5c83-5422-9f13-132745190e9b', 'e70c24f8-40ff-5fc9-97bb-517761e1e271', 'Bottle', '70', 1),
  ('d3f2ee82-7e95-504d-8bcb-e691f96a934d', 'c9e658e9-19e6-570b-b390-7abc91b15d06', 'Bottle', '72', 1),
  ('9c730382-2a10-5c99-96af-4c65eee99db0', '5058412e-97c4-57a9-95f6-2674156958ac', 'Bottle', '70', 1),
  ('9c8455e2-3bbe-5028-89b0-2b17691ca6f7', 'd4191b99-3e5d-5d98-97ec-827e7d7e8a05', 'Bottle', '75', 1),
  ('082ba54c-d672-5556-aded-7957722715d2', '265d561e-23d3-52cc-9da9-e7e2f195c8c1', 'Bottle', '55', 1),
  ('586f4f5a-6e0b-5e17-a259-3220fb0c4d33', 'e4175bd7-9ec9-57f1-b2ef-a6825d42776d', 'Bottle', '65', 1),
  ('e2f26410-cfd3-5651-be5e-e0ef1018f188', '541f1c3f-13ab-5d10-968e-53bfe11a2ac3', 'Bottle', '70', 1),
  ('b72a2f09-e374-5125-b82e-37fb5bf8573a', '738eb521-0f4c-566e-bd43-585454bee99d', 'Bottle', '70', 1),
  ('929644ae-25a6-5b13-bf1b-545f1bc6a47a', '2cd251f2-db1e-5798-b17c-45581ad38b22', 'Bottle', '70', 1),
  ('7a78dadc-5a01-53ff-9130-f02c1ed83ce7', '93148e6b-02bf-5bfc-bc9b-5a2ba590589b', 'Bottle', '65', 1),
  ('692c2a8d-53a8-561e-9e03-f716ec7d6688', 'db5c44d1-763a-58db-b03a-d63fac16ef36', 'Small', '32', 1),
  ('a0844a8d-d82b-52a9-8813-befcd6d2576b', 'db5c44d1-763a-58db-b03a-d63fac16ef36', 'Large', '42', 2),
  ('be137040-ce32-5e16-a5a3-6ce19c77c1aa', 'dcd8297f-a8b5-50b4-9a6b-aa99c25d4b19', 'Small', '15', 1),
  ('8ddeec9b-efdb-52dd-bb76-d9d124df8b10', 'dcd8297f-a8b5-50b4-9a6b-aa99c25d4b19', 'Large', '25', 2);

-- ---- options (the crêpe toppings) -------------------------------------------
-- Modelled so nothing is lost on the way in. Not exposed in the editor.
insert into public.menu_item_options (id, item_id, name, price, sort_order) values
  ('623d903a-db48-5774-b104-f51c1d0d88db', '4be780a0-a50d-5aea-976a-d48f12dc8e96', 'Fresh strawberry', '1.00', 1),
  ('07c87ef1-513e-558e-a72e-a8edb8a6d404', '4be780a0-a50d-5aea-976a-d48f12dc8e96', 'Fresh banana', '1.00', 2),
  ('0e2f9e32-54c1-5f58-8d05-8241eea70cea', '4be780a0-a50d-5aea-976a-d48f12dc8e96', 'Strawberry jam', '0.50', 3),
  ('44256ab2-0ca3-5159-9972-bb15adc3947e', '4be780a0-a50d-5aea-976a-d48f12dc8e96', 'Mixed berry jam', '0.50', 4),
  ('0231cc05-f292-5a51-98a7-eb7de6d4f3b4', '4be780a0-a50d-5aea-976a-d48f12dc8e96', 'Nutella', '2.00', 5),
  ('121deab0-5cdf-5e37-85b4-0c4fb86cf239', '4be780a0-a50d-5aea-976a-d48f12dc8e96', 'Whipped cream', '0.50', 6),
  ('caa64778-3183-5c7e-988f-8d473b4f7121', '4be780a0-a50d-5aea-976a-d48f12dc8e96', 'Vanilla ice cream', '3.00', 7);

-- ---- section copy ----------------------------------------------------------
-- Labels come from tools/copy-labels.mjs and are the owner's words, not keys.
-- max_length is set on the animated headlines only, and is provisional.
insert into public.site_copy (key, page, section, label, help, value, max_length, sort_order) values
  ('hero.eyebrow', 'index', 'Hero', 'Small line above the name', null, 'Murray Hill · Manhattan', null, 10),
  ('hero.sub', 'index', 'Hero', 'Line under the name', 'The wide spacing around the ✦ is deliberate — keep it if you edit this.', 'Café  ✦  Wine Bar', null, 20),
  ('hero.desc', 'index', 'Hero', 'Opening sentence', 'Starting a new line here puts one on the page.', E'Two floors on East 34th Street where Georgian cooking,\nnatural wine and coffee share one table.', null, 30),
  ('hero.ctaPrimary', 'index', 'Hero', 'First button', null, 'See the Menus', null, 40),
  ('hero.ctaSecondary', 'index', 'Hero', 'Second button', null, 'The Wine Bar', null, 50),
  ('story.label', 'index', 'The Idea', 'Section tag', null, 'The Idea', null, 60),
  ('story.headline', 'index', 'The Idea', 'Headline', null, 'Georgian cooking for a Manhattan morning.', 72, 70),
  ('story.lead', 'index', 'The Idea', 'Opening paragraph', 'Put *asterisks* around words to set them in italic.', 'Aromati, from the Georgian word for *aroma*, is a bi-level café and wine bar in Murray Hill, where American coffee culture meets the oldest food and wine traditions in Europe.', null, 80),
  ('story.body', 'index', 'The Idea', 'Second paragraph', null, 'Downstairs, an open kitchen and coffee bar move at the pace of the city: espresso pulled, matcha whisked, khachapuri blistering in the oven. Upstairs, the room slows down into burgundy walls, tufted leather, cane and oak, and low globe light, a dining room and wine bar built for long evenings.', null, 90),
  ('story.quote', 'index', 'The Idea', 'Pull quote', null, 'Georgia has been making wine for eight thousand years. We think it belongs at the table, whatever the occasion.', null, 100),
  ('kitchen.label', 'index', 'The Kitchen', 'Section tag', null, 'The Kitchen', null, 110),
  ('kitchen.headline', 'index', 'The Kitchen', 'Headline', null, 'Bread, cheese, and broth: a few staples of the Georgian table.', 72, 120),
  ('kitchen.lede', 'index', 'The Kitchen', 'Paragraph under the headline', null, 'Everything comes out of the open kitchen on the ground floor. Khachapuri is blistered to order and khinkali is pleated by hand.', null, 130),
  ('kitchen.reelLabel', 'index', 'The Kitchen', 'Caption above the photo strip', null, 'A few plates', null, 140),
  ('kitchen.reelNote', 'index', 'The Kitchen', 'Small note beside the caption', null, 'photographed in the room', null, 150),
  ('cafe.label', 'index', 'The Café', 'Section tag', null, 'The Café', null, 160),
  ('cafe.headline', 'index', 'The Café', 'Headline', null, 'Downstairs runs on espresso.', 72, 170),
  ('cafe.lede', 'index', 'The Café', 'Paragraph under the headline', null, 'The ground floor is a New York coffee bar with espresso drinks, matcha, and pastries for the morning.', null, 180),
  ('cafe.card1.title', 'index', 'The Café', 'Card 1 — drink', null, 'Tiramisu Latte', null, 190),
  ('cafe.card1.note', 'index', 'The Café', 'Card 1 — description', null, 'mascarpone cream, cocoa, a ladyfinger on top', null, 200),
  ('cafe.card2.title', 'index', 'The Café', 'Card 2 — drink', null, 'Maple Syrup Iced Latte', null, 210),
  ('cafe.card2.note', 'index', 'The Café', 'Card 2 — description', null, 'topped with silky maple cold foam', null, 220),
  ('cafe.card3.title', 'index', 'The Café', 'Card 3 — drink', null, 'Fruit Matchas', null, 230),
  ('cafe.card3.note', 'index', 'The Café', 'Card 3 — description', null, 'strawberry, mango & blueberry, layered over ice', null, 240),
  ('cafe.card4.title', 'index', 'The Café', 'Card 4 — drink', null, 'The Classics', null, 250),
  ('cafe.card4.note', 'index', 'The Café', 'Card 4 — description', null, 'flat whites & cappuccinos, poured properly', null, 260),
  ('cafe.cta', 'index', 'The Café', 'Sentence above the button', null, 'The drinks menu includes espresso, matcha, chai, smoothies, and cold drinks.', null, 270),
  ('cafe.ctaButton', 'index', 'The Café', 'Button', null, 'See the Drinks Menu', null, 280),
  ('wine.label', 'index', 'The Wine Bar', 'Section tag', null, 'The Wine Bar', null, 290),
  ('wine.headline', 'index', 'The Wine Bar', 'Headline', null, 'A wine list shaped by Georgia.', 72, 300),
  ('wine.lede', 'index', 'The Wine Bar', 'Paragraph under the headline', null, 'Upstairs, the list brings together qvevri ambers, Saperavi, natural wines, and a short European selection. Wines are available by the glass or bottle, with pairings for the table.', null, 310),
  ('wine.note1.title', 'index', 'The Wine Bar', 'Note 1 — title', null, 'Amber', null, 320),
  ('wine.note1.text', 'index', 'The Wine Bar', 'Note 1 — description', null, 'Amber wines bring notes of honey, spice, dried fruit, and citrus.', null, 330),
  ('wine.note2.title', 'index', 'The Wine Bar', 'Note 2 — title', null, 'Saperavi', null, 340),
  ('wine.note2.text', 'index', 'The Wine Bar', 'Note 2 — description', null, 'Saperavi is a Georgian red with dark berry, plum, and cherry notes.', null, 350),
  ('wine.note3.title', 'index', 'The Wine Bar', 'Note 3 — title', null, 'Qvevri', null, 360),
  ('wine.note3.text', 'index', 'The Wine Bar', 'Note 3 — description', null, 'The list includes qvevri wines in both amber and red styles.', null, 370),
  ('wine.hours', 'index', 'The Wine Bar', 'Small line about the room', null, 'Second floor · wine bar', null, 380),
  ('wine.ctaButton', 'index', 'The Wine Bar', 'Button', null, 'Read the Wine List', null, 390),
  ('gallery.label', 'index', 'The Room', 'Section tag', null, 'The Room', null, 400),
  ('gallery.headline', 'index', 'The Room', 'Headline', null, 'Cane, leather, burgundy — and light that lingers.', 72, 410),
  ('visit.label', 'index', 'Visit', 'Section tag', null, 'Visit', null, 420),
  ('visit.headline', 'index', 'Visit', 'Headline', 'Starting a new line here puts one on the page.', E'Come say hello,\nMurray Hill.', 72, 430),
  ('food.label', 'food', 'Food menu', 'Section tag', null, 'The Kitchen', null, 440),
  ('food.headline', 'food', 'Food menu', 'Page title', null, 'The Food Menu', 32, 450),
  ('food.lede', 'food', 'Food menu', 'Paragraph under the title', null, 'Everything comes out of the open kitchen on the ground floor. Khachapuri is blistered to order and khinkali is pleated by hand. Served all day.', null, 460),
  ('food.footNote', 'food', 'Food menu', 'Note at the foot of the menu', null, '…and salads, stews, toast & sweets in between.', null, 470),
  ('food.footButton', 'food', 'Food menu', 'Button at the foot of the menu', null, 'Come Hungry', null, 480),
  ('drinks.label', 'drinks', 'Drinks menu', 'Section tag', null, 'The Café', null, 490),
  ('drinks.headline', 'drinks', 'Drinks menu', 'Page title', null, 'Hot & Cold Drinks', 32, 500),
  ('drinks.lede', 'drinks', 'Drinks menu', 'Paragraph under the title', null, 'The ground floor is a New York coffee bar: espresso pulled properly, matcha whisked to order, smoothies blended fresh. From seven in the morning.', null, 510),
  ('drinks.footNote', 'drinks', 'Drinks menu', 'Note at the foot of the menu', null, 'Ask about drink customizations.', null, 520),
  ('drinks.footButton', 'drinks', 'Drinks menu', 'Button at the foot of the menu', null, 'Find the Café', null, 530),
  ('wineList.label', 'wine', 'Wine list', 'Section tag', null, 'The Wine Bar', null, 540),
  ('wineList.headline', 'wine', 'Wine list', 'Page title', null, 'The Wine List', 32, 550),
  ('wineList.lede', 'wine', 'Wine list', 'Paragraph under the title', null, 'Qvevri ambers, Saperavi and natural bottles chosen for the table, alongside a short European list. Poured by the glass or the bottle on the second floor.', null, 560),
  ('wineList.footNote', 'wine', 'Wine list', 'Note at the foot of the list', null, 'Wines are available by the glass or bottle. The selection may change.', null, 570),
  ('wineList.footButton', 'wine', 'Wine list', 'Button at the foot of the list', null, 'Plan a Visit', null, 580),
  ('faq.label', 'faq', 'FAQ page', 'Section tag', null, 'Good to Know', null, 590),
  ('faq.headline', 'faq', 'FAQ page', 'Page title', null, 'Questions, answered.', 32, 600),
  ('faq.lede', 'faq', 'FAQ page', 'Paragraph under the title', null, 'The things guests ask most often — when to come, what the upstairs room is like, and how to plan something bigger than a table for two.', null, 610),
  ('faq.footNote', 'faq', 'FAQ page', 'Note at the foot of the page', null, 'Still wondering? Call us — someone is always in.', null, 620);

-- ---- did it all land? ------------------------------------------------------
-- A partial apply leaves a menu quietly missing its last section. This turns
-- that into an error at the moment it happens.
do $$
declare n integer;
begin
  select count(*) into n from public.menu_courses;
  if n <> 17 then raise exception 'menu_courses: expected 17 rows, found %', n; end if;
  select count(*) into n from public.menu_items;
  if n <> 84 then raise exception 'menu_items: expected 84 rows, found %', n; end if;
  select count(*) into n from public.menu_item_pours;
  if n <> 26 then raise exception 'menu_item_pours: expected 26 rows, found %', n; end if;
  select count(*) into n from public.menu_item_options;
  if n <> 7 then raise exception 'menu_item_options: expected 7 rows, found %', n; end if;
  select count(*) into n from public.site_copy;
  if n <> 62 then raise exception 'site_copy: expected 62 rows, found %', n; end if;
end $$;
