-- ============================================================================
-- Phase 6 — the photographs
--
-- Generated by tools/gen-photo-sql.mjs from tools/photo-slots.mjs and
-- data/seed-photos.js. Do not edit by hand; edit those and run it again.
--
-- Three things happen here, and the order matters:
--
--   1. photos gets an is_decorative column, and the alt rule is corrected
--   2. one row per slot, 28 of them
--   3. the storage bucket the uploads go into, with its limits and policies
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. Decoration is not a missing description
--
-- The original table said: a photograph with a file must have alt text. That is
-- right for a photograph and wrong for a backdrop. 4 of the 28 slots are
-- texture — behind a scrim, behind a gradient, aria-hidden, carrying alt="" on
-- purpose — and forcing a description onto those would make a screen reader
-- announce the wallpaper.
--
-- So the rule becomes: a photograph that is content and has a file must have a
-- description. Decoration is exempt, and which slots are decoration is the
-- markup's business rather than the owner's, which is why is_decorative is
-- protected by the trigger below rather than offered in the editor.
-- ----------------------------------------------------------------------------

alter table public.photos
  add column if not exists is_decorative boolean not null default false;

alter table public.photos drop constraint if exists photos_alt_required_with_image;
alter table public.photos add constraint photos_alt_required_with_image
  check (is_decorative or storage_path is null or length(btrim(alt)) > 0);

comment on column public.photos.is_decorative is
  'The image is texture, not content: aria-hidden, alt="" on purpose. Set by the markup, never by the editor.';


-- ----------------------------------------------------------------------------
-- 2. Only the photograph and its description are the owner's
--
-- Same reasoning as only_value_may_change() on site_copy: row level security
-- grants an UPDATE on a row, not on a column. Without this an editor could
-- rename a slot — and a renamed slot is a photograph that stops appearing on
-- the site, with no error anywhere to say why.
--
-- storage_path, source_path, alt, width and height are the owner's. slot,
-- label, is_decorative and sort_order describe where the picture goes, and
-- that is decided by the markup.
-- ----------------------------------------------------------------------------

create or replace function public.only_photo_may_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.id <> old.id or new.slot <> old.slot then
    raise exception 'The photograph slot "%" cannot be renamed or moved. Only the picture and its description can be changed.', old.slot;
  end if;
  new.label         = old.label;
  new.is_decorative = old.is_decorative;
  new.sort_order    = old.sort_order;
  return new;
end;
$$;

drop trigger if exists photos_photo_only on public.photos;
create trigger photos_photo_only
  before update on public.photos
  for each row execute function public.only_photo_may_change();

-- A described photograph needs its description. The CHECK above already refuses
-- it, but a CHECK constraint's message names a constraint, and the person
-- reading it is a café owner. This says the same thing in their language, and
-- tools/test-admin.mjs holds the editor to the identical sentence.
create or replace function public.check_photo_alt()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if not new.is_decorative and new.storage_path is not null
     and length(btrim(new.alt)) = 0 then
    raise exception 'The photograph "%" needs a short description of what is in it. It is what someone using a screen reader hears in place of the picture, and what shows if the image ever fails to load.', new.label;
  end if;
  return new;
end;
$$;

drop trigger if exists photos_alt_check on public.photos;
create trigger photos_alt_check
  before insert or update on public.photos
  for each row execute function public.check_photo_alt();


-- ----------------------------------------------------------------------------
-- 3. One row per slot
--
-- storage_path is null on every one of them, which is the whole design: null
-- means "the photograph the site shipped with", and that photograph is in the
-- markup rather than in a bucket. So this table starts out changing nothing,
-- and a project that has never had an upload renders exactly the site in git.
--
-- The descriptions are the ones already in the markup, so the editor opens
-- showing what is actually on the page rather than 24 empty boxes.
-- ----------------------------------------------------------------------------

insert into public.photos (slot, label, alt, is_decorative, width, height, sort_order) values
  ('hero.main', 'The photograph behind the opening headline', 'The upstairs dining room at Aromati — cane chairs, tufted leather, burgundy walls', false, 1672, 941, 10),
  ('story.a', 'The Idea — the upper photograph', 'Burgundy wall, organic mirror and cane chairs inside Aromati', false, 1023, 682, 20),
  ('story.b', 'The Idea — the lower photograph', 'Golden hour light across the window tables at Aromati', false, 1088, 680, 30),
  ('kitchen.plate1', 'The Kitchen strip — 1st photograph', 'Adjaruli khachapuri — cheese boat with egg yolk and butter', false, 1100, 566, 40),
  ('kitchen.plate2', 'The Kitchen strip — 2nd photograph', 'Khinkali — Georgian soup dumplings', false, 688, 550, 50),
  ('kitchen.plate3', 'The Kitchen strip — 3rd photograph', 'Imeruli khachapuri — round cheese-filled bread', false, 1100, 578, 60),
  ('kitchen.plate4', 'The Kitchen strip — 4th photograph', 'Eggplant rolls with walnut paste and pomegranate', false, 1100, 576, 70),
  ('kitchen.plate5', 'The Kitchen strip — 5th photograph', 'Assorted pkhali with warm cornbread', false, 1100, 546, 80),
  ('kitchen.plate6', 'The Kitchen strip — 6th photograph', 'Shoti’s puri, canoe-shaped Georgian bread with ajika', false, 1100, 566, 90),
  ('kitchen.plate7', 'The Kitchen strip — 7th photograph', 'Tolma — grape leaves with garlic sour cream', false, 1100, 560, 100),
  ('kitchen.plate8', 'The Kitchen strip — 8th photograph', 'The Georgian salad with walnut dressing', false, 1100, 574, 110),
  ('kitchen.plate9', 'The Kitchen strip — 9th photograph', 'Layered honey cake with pistachio', false, 1100, 570, 120),
  ('cafe.card1', 'The Café — 1st card', 'Tiramisu latte in a branded Aromati cup', false, 1088, 1446, 130),
  ('cafe.card2', 'The Café — 2nd card', 'Maple syrup iced latte with cold foam', false, 878, 1200, 140),
  ('cafe.card3', 'The Café — 3rd card', 'Three fruit matcha lattes held in a stack', false, 878, 1200, 150),
  ('cafe.card4', 'The Café — 4th card', 'Flat white with rosetta latte art', false, 878, 1200, 160),
  ('wine.backdrop', 'The Wine Bar — the background behind the section', '', true, 1088, 1445, 170),
  ('wine.board', 'The Wine Bar — the board photograph', 'Saperavi and a cheese and charcuterie board at Aromati', false, 1089, 1089, 180),
  ('gallery.g1', 'The gallery — 1st photograph', 'The full dining room — banquette, mirrors, pendant globes', false, 1535, 1024, 190),
  ('gallery.g2', 'The gallery — 2nd photograph', 'Tables set with wine glasses beneath pendant lights', false, 1023, 1139, 200),
  ('gallery.g3', 'The gallery — 3rd photograph', 'A bottle of Saperavi with an Aromati wine bag', false, 937, 1187, 210),
  ('gallery.g4', 'The gallery — 4th photograph', 'Georgian salad with walnut dressing and pomegranate', false, 1735, 906, 220),
  ('gallery.g5', 'The gallery — 5th photograph', 'Cappuccino with heart latte art', false, 1085, 1450, 230),
  ('gallery.g6', 'The gallery — 6th photograph', 'Strawberry and goat cheese salad', false, 1732, 908, 240),
  ('visit.storefront', 'Visit — the storefront photograph', 'The Aromati storefront on East 34th Street', false, 1456, 1080, 250),
  ('menuFood.masthead', 'Food menu — the banner photograph', '', true, 1747, 900, 260),
  ('menuDrinks.masthead', 'Drinks menu — the banner photograph', '', true, 1083, 542, 270),
  ('menuWine.masthead', 'Wine list — the banner photograph', '', true, 1088, 1445, 280)
on conflict (slot) do nothing;

do $$
declare n integer;
begin
  select count(*) into n from public.photos;
  if n <> 28 then raise exception 'photos: expected 28 rows, found %', n; end if;
end $$;


-- ============================================================================
-- 4. The bucket
--
-- file_size_limit and allowed_mime_types are set HERE, on the bucket, and not
-- only in the editor. The editor's checks are a courtesy that lets someone find
-- out before they wait for an upload; they are not a control. Anyone holding
-- the owner's token can post straight at the storage API and never load
-- admin.js at all. See memory.md, "Storage abuse".
--
-- public = true means /storage/v1/object/public/site-photos/… serves the file
-- without consulting row level security, which is what the site needs: a
-- visitor is not signed in. It does NOT make the bucket listable — that is the
-- select policy below, and it is deliberately restricted to the owner. A public
-- bucket with a select policy for anon is an enumerable bucket.
--
-- One bucket per feature, not one shared bucket. Uptown's reasoning, worth
-- keeping: share a bucket and one feature's orphan cleanup decides the fate of
-- another feature's files.
--
-- 3 MB is generous for a photograph that has already been resized to 2000px and
-- re-encoded as webp in the browser — a 2000px webp of a café interior is
-- usually under 400 KB. The headroom is for the original, which is kept
-- alongside so a crop can be undone, and which is whatever the camera or the
-- phone produced.
--
-- Three types, and no fourth. webp is what the editor writes; jpeg and png are
-- what an original arrives as. SVG is deliberately absent and must stay absent:
-- it is the one image format that can contain a script, and a public bucket
-- serving one from this project's own origin would run it there.
-- ============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('site-photos', 'site-photos', true, 3145728,
        array['image/webp', 'image/jpeg', 'image/png'])
on conflict (id) do update set
  public            = excluded.public,
  file_size_limit   = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;


-- ---- policies on the objects themselves -------------------------------------
-- Writes are the allowlisted owner and nobody else — the same is_owner() every
-- content table uses, so there is one answer to "who may change this site" and
-- it is stored in one place.
--
-- The select policy is what makes the bucket *listable* through the API. The
-- owner needs it to see what is in there; anon does not, and granting it would
-- turn every uploaded file into something a stranger can enumerate even though
-- each individual URL is already public.

drop policy if exists "site-photos owner insert" on storage.objects;
create policy "site-photos owner insert"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'site-photos' and public.is_owner());

drop policy if exists "site-photos owner update" on storage.objects;
create policy "site-photos owner update"
  on storage.objects for update to authenticated
  using (bucket_id = 'site-photos' and public.is_owner())
  with check (bucket_id = 'site-photos' and public.is_owner());

drop policy if exists "site-photos owner delete" on storage.objects;
create policy "site-photos owner delete"
  on storage.objects for delete to authenticated
  using (bucket_id = 'site-photos' and public.is_owner());

drop policy if exists "site-photos owner list" on storage.objects;
create policy "site-photos owner list"
  on storage.objects for select to authenticated
  using (bucket_id = 'site-photos' and public.is_owner());
